//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteThucPhamSach_VS2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class advertis
    {
        public int id { get; set; }
        public string link { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> start_time { get; set; }
        public Nullable<int> width { get; set; }
        public Nullable<int> height { get; set; }
        public Nullable<int> order { get; set; }
        public string url { get; set; }
        public string target { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
