//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteThucPhamSach_VS2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class @event
    {
        public int id { get; set; }
        public Nullable<int> admin_id { get; set; }
        public string image { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public Nullable<System.DateTime> start_time { get; set; }
        public Nullable<System.DateTime> end_time { get; set; }
        public Nullable<bool> top_hot { get; set; }
        public Nullable<bool> status { get; set; }
    
        public virtual admin admin { get; set; }
    }
}
