//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteThucPhamSach_VS2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int id { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string image { get; set; }
        public string more_images { get; set; }
        public string detail { get; set; }
        public string keywords { get; set; }
        public Nullable<int> includeVAT { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> price_promotion { get; set; }
        public Nullable<bool> top_hot { get; set; }
        public Nullable<int> provider_id { get; set; }
        public string menu_id { get; set; }
        public Nullable<System.DateTime> start_time { get; set; }
        public Nullable<int> total_product { get; set; }
        public Nullable<int> total_sold { get; set; }
        public Nullable<bool> special { get; set; }
        public Nullable<int> view_count { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
